# This will be changed to a singular triggering the builds and commiting the files.
name: Build and Deploy
on:
  push:
    branches: 
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          cd ./employee-info
          npm install
          cd ..
          cd ./sample
          npm install
      
      - name: Build Apps
        run: chmod +x ./.ci/build.sh ; sh ./ci/build.sh
      
      - name: Deploy Apps
        env:
           DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
           USERNAME: ${{ secrets.USERNAME }}
           EMAIL: ${{ secrets.EMAIL }}
        run: chmod +x ./.ci/deploy.sh ; sh ./.ci/deploy.sh
          
